FrontBundle\Entity\Status:
    type: entity
    table: null
    repositoryClass: FrontBundle\Repository\StatusRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
        color:
            type: string
            length: 255
        code:
            type: string
            length: 255
        downloaded:
            type: boolean
    lifecycleCallbacks: {  }
