<?php

namespace FrontBundle\Repository;

/**
 * TorrentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TorrentRepository extends \Doctrine\ORM\EntityRepository
{

    /**
     * @param $ids
     * @return array
     */
    public function getUnavailableTorrents($ids)
    {
        return $this->createQueryBuilder('p')
            ->where('p.idTransmission NOT IN (:ids)')
            ->setParameter('ids', $ids)
            ->getQuery()
            ->getResult();
    }

    /**
     * @param $date
     * @return array
     */
    public function getLastUpdTorrents($date) {
        return $this->createQueryBuilder('p')
            ->where('p.date_upd >= :d')
            ->setParameter('d', $date)
            ->getQuery()
            ->getResult();
    }

}
