<?php

namespace FrontBundle\Repository;

/**
 * TorrentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TorrentRepository extends \Doctrine\ORM\EntityRepository
{
}
